Added Web server project

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,12 +1,23 @@
 #!/usr/bin/env bash
-#transfer file 'file' to a server
+# Transfers a file to a remote server via SCP
 #scp / path/to/file username@a:/path/to/destination
-#handcoded: scp -i ~/.ssh/id_rsa README.md ubuntu@35.229.61.60
+#handcoded: scp -i ~/.ssh/id_rsa README.md ubuntu@54.173.231.174
 
-#if number of arguments is >= 3
-if [ $# -lt 4]
-then
-    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+if [ $# -lt 4 ]; then
+    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+    exit 1
+fi
+
+PATH_TO_FILE="$1"
+IP="$2"
+USERNAME="$3"
+PATH_TO_SSH_KEY="$4"
+
+scp -o StrictHostKeyChecking=no -i "$PATH_TO_SSH_KEY" "$PATH_TO_FILE" "$USERNAME@$IP:~/"
+
+if [ "$?" -eq 0 ]; then
+    echo "File transfer completed successfully"
 else
-    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
+    echo "File transfer failed"
+    exit 1
 fi
